theme: jekyll-theme-minimal
title: 350 Методи і засоби комп'ютерних інформаційних технологій
description: Навчально-методичний комплекс для груп 351, 352 з дисципліни "Методи і засоби комп'ютерних інформаційних технологій"